import type { HealthReport, RepoAnalysis } from "../types/index.js";

const BADGE = (v: boolean) => (v ? "✅" : "❌");

const SEVERITY_ICON: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🔵",
};

const PRIORITY_ICON: Record<string, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🔵",
};

/**
 * Builds a full Markdown health report from a completed RepoAnalysis.
 * Pure function — no side effects, no async, no external calls.
 */
export function generateMarkdownReport(
  analysis: RepoAnalysis,
  score: number,
  grade: HealthReport["grade"],
  summary: string
): string {
  const lines: string[] = [
    `# repo-critic-ai Report: ${analysis.owner}/${analysis.name}`,
    "",
    `**Health Score: ${score}/100 (${grade})**`,
    "",
    `> ${summary}`,
    "",
    "---",
    "",
  ];

  // ── README ───────────────────────────────────────────────────────────────
  lines.push("## README Analysis", "");
  if (!analysis.readme.success) {
    lines.push(`> ⚠️ Error: ${analysis.readme.error}`, "");
  } else {
    const r = analysis.readme.data;
    lines.push("| Check | Result |", "|-------|--------|");
    lines.push(`| Present | ${BADGE(r.present)} |`);
    lines.push(`| Word count | ${r.lengthWords} |`);
    lines.push(`| Install section | ${BADGE(r.hasInstallSection)} |`);
    lines.push(`| Usage section | ${BADGE(r.hasUsageSection)} |`);
    lines.push(`| Code examples | ${BADGE(r.hasExamples)} |`);
    lines.push(`| Score | **${r.score}/100** |`);
    lines.push("");
  }

  // ── SECURITY ─────────────────────────────────────────────────────────────
  lines.push("## Security Findings", "");
  if (!analysis.security.success) {
    lines.push(`> ⚠️ Error: ${analysis.security.error}`, "");
  } else if (analysis.security.data.length === 0) {
    lines.push("✅ No security issues detected.", "");
  } else {
    lines.push("| Severity | Category | File | Description |");
    lines.push("|----------|----------|------|-------------|");
    for (const f of analysis.security.data) {
      const icon = SEVERITY_ICON[f.severity] ?? "";
      lines.push(`| ${icon} ${f.severity} | ${f.category} | \`${f.file}\` | ${f.description} |`);
    }
    lines.push("");
  }

  // ── TODOS ─────────────────────────────────────────────────────────────────
  lines.push("## TODO / FIXME Items", "");
  if (!analysis.todos.success) {
    lines.push(`> ⚠️ Error: ${analysis.todos.error}`, "");
  } else if (analysis.todos.data.length === 0) {
    lines.push("✅ No TODO / FIXME comments found in scanned files.", "");
  } else {
    lines.push("| Priority | Type | File | Line | Text |");
    lines.push("|----------|------|------|------|------|");
    const shown = analysis.todos.data.slice(0, 20);
    for (const t of shown) {
      const icon = PRIORITY_ICON[t.priority] ?? "";
      lines.push(
        `| ${icon} ${t.priority} | \`${t.type}\` | \`${t.file}\` | ${t.line} | ${t.text} |`
      );
    }
    if (analysis.todos.data.length > 20) {
      lines.push("", `*… and ${analysis.todos.data.length - 20} more.*`);
    }
    lines.push("");
  }

  // ── ISSUES ────────────────────────────────────────────────────────────────
  lines.push("## Issue Quality", "");
  if (!analysis.issues.success) {
    lines.push(`> ⚠️ Error: ${analysis.issues.error}`, "");
  } else if (analysis.issues.data.length === 0) {
    lines.push("ℹ️ No open issues found.", "");
  } else {
    const avg = Math.round(
      analysis.issues.data.reduce((s, i) => s + i.qualityScore, 0) / analysis.issues.data.length
    );
    lines.push(
      `Average issue quality: **${avg}/100** (${analysis.issues.data.length} open issues)`,
      ""
    );
    lines.push("| # | Title | Description | Labels | Score |");
    lines.push("|---|-------|-------------|--------|-------|");
    for (const issue of analysis.issues.data.slice(0, 10)) {
      lines.push(
        `| ${issue.number} | ${issue.title.slice(0, 50)} | ${BADGE(issue.hasDescription)} | ${BADGE(issue.hasLabels)} | ${issue.qualityScore} |`
      );
    }
    lines.push("");
  }

  lines.push("---", "");
  lines.push(
    `*Generated by repo-critic-ai on ${new Date().toISOString()}*`,
    `*Repository: ${analysis.repoUrl}*`
  );

  return lines.join("\n");
}
